-- migrate:up
ALTER TABLE posts MODIFY COLUMN text VARCHAR(3000) NOT NULL;
ALTER TABLE posts RENAME COLUMN text to context;
ALTER TABLE posts ADD COLUMN creaetd_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts ADD COLUMN updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;

-- migrate:down

